### ISSUE TITLE
Implement readable `stringify` function for parsing result of ESMeta

### ISSUE THREAD

**Issue by jhnaldo** [es-meta/es-meta#7]
The current string form of a parsing result of ESMeta does not have space as follows:
```
Return_completionRecord_astheCompletionRecordofthisabstractoperation.
```
Please implement a `stringify` function that produces the following string:
```
Return _completionRecord_ as the Completion Record of this abstract operation.
```

**Comment by dimenerno** [comment]
7426f4d3f5da6eb507f2b66b88f8782004dba9aa
